# Generated by Django 3.2.9 on 2021-11-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_trusted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(editable=False)),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('data', models.JSONField()),
                ('timestamp', models.DateTimeField()),
                ('validation_state', models.CharField(choices=[('NV', 'Processing Pending'), ('IN', 'Invalid'), ('VA', 'Valid')], default='NV', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('schema', models.JSONField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='validationschema',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='validation.category_name'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('category', 'name', 'session_id', 'timestamp'), name='event.category_name'),
        ),
    ]
